### PR TITLE
Recommendations for Readme

### PR DESCRIPTION
**Pull request by bitjson**

### CODE REVIEW

**Comment by nacardin** [comment]
+1

**Comment by graingert** [comment]
hey @bitjson can you rebase this and make sure travis passes?

**Comment by bitjson** [comment]
@graingert looks like it's all good. Thanks for the project!

**Comment by graingert** [comment]
hey @bitjson can you rebase this?

**Comment by bitjson** [comment]
Closing in favor of https://github.com/graingert/slimerjs/pull/23.

**Pull request closed without merging**
