### PR TITLE
merge upstream phantomjs into slimerjs

### PR DESCRIPTION
**Pull request by thhalm**
Merged master from https://github.com/Medium/phantomjs.git (d281c9a7280eb5002a0158cd1f2978773fdb4b57) into slimerjs (see #17)

### CODE REVIEW

**Comment by graingert** [comment]
Looks good, can you add `t.halm@talkwalker.com` to https://github.com/settings/emails#new_user_email

What was your strategy to handle the differences between upstream and this repo?

**Comment by thhalm** [comment]
Ok. Email added.

Regarding the differences: I took the phantomjs/master code as "leading" and did just a search/replace "phantomjs => slimerjs" in first place.

Afterwards a copied the "download url" logic to the new method `getDownloadUrl`

**Comment by graingert** [comment]
Awesome, what about the other doc changes we've added?

**Comment by thhalm** [comment]
I did at merge for the README.md file.

Added two new sections (anlogical to changes from phantomjs/master)
- Deciding Where To Get SlimerJS
- Troubleshooting

No already existing documentation was changed or removed in that file.

As the merge commit only changed 3 files no other doc were changed...

**Pull request merged**
