### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@nicks hey, is there any way we can genericise phantomjs-prebuilt so I don't have to keep merging from upstream?

There are other -prebuilt packages floating around that are getting behind changes in phantomjs-prebuilt

**Comment by nicks** [comment]
it's hard to say, because i have no idea what you're doing or why you're
doing it!

**Comment by graingert** [comment]
I'm packaging a binary similar yet different to phantomjs

**Comment by nicks** [comment]
We don't have any plans to genericise the logic, but we welcome anyone to try it.

There are also a couple "generic" binary downloaders in NPM (e.g., https://www.npmjs.com/package/bin-wrapper). We audited them a while back, but didn't find anything sufficient for phantomjs's needs. Most were missing basic error handling and caching. It's also important to us to support multi-platform repos (i.e., being able to adapt the modules to your platform with an `npm rebuild`). But they might meet your needs.

**Pull request merged**
